import commentIcon from "../../assets/icons/commentIcon.png";
import createIcon from "../../assets/icons/createIcon.png";
import addIcon from "../../assets/icons/addIcon.png";
import closeIcon from "../../assets/icons/closeIcon.png";
import sendIcon from "../../assets/icons/sendIcon2.png";
import cancelIcon from "../../assets/icons/cancelIcon.png";
import infoIcon from "../../assets/icons/infoIcon.png";
import UNlogo from "../../assets/logos/unLogo.png";
import searchIcon from "../../assets/icons/searchIcon.png";
import goBackIcon from "../../assets/icons/goBackIcon.png";
import pencilIcon from "../../assets/icons/pencilIcon.png";
import createParcheIcon from "../../assets/icons/createParcheIcon.png";
import createParcheIcon2 from "../../assets/icons/createParcheIcon2.png";
import createParcheIcon3 from "../../assets/icons/createParcheIcon3.png";
import reviewIcon from "../../assets/icons/reviewIcon.png";
import favoriteIcon from "../../assets/icons/favoriteIcon.png";
import suggestIcon from "../../assets/icons/suggestIcon.png";
import sendIcon2 from "../../assets/icons/sendIcon.png";
import addParche from "../../assets/icons/addParche.png";
import minusIcon from "../../assets/icons/minusIcon.png";
import ActivitySmallCard from "./components/ActivitySmallCard";
import ParcheSmallCard from "./components/ParcheSmallCard";
import MemberCircle from "./components/MemberCircle";
import CommentCard from "./components/CommentCard";
import CommentForm from "./components/CommentForm";
import ActivityCharacteristics from "../../components/ActivityCharacteristics";
import CreateActivityForm from "../../components/CreateActivityForm";

export {commentIcon,sendIcon,cancelIcon, infoIcon, closeIcon,addParche, UNlogo,searchIcon, goBackIcon, pencilIcon, createParcheIcon, createParcheIcon2,createParcheIcon3, reviewIcon, favoriteIcon, suggestIcon, sendIcon2,minusIcon,createIcon, addIcon, ActivitySmallCard, ParcheSmallCard, MemberCircle, CommentCard, CommentForm, ActivityCharacteristics, CreateActivityForm}